# 1
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"

# 2
default_platform(:ios)

# 3
platform :ios do

  # 4
  lane :build do
    scan
    #cert
    #sigh

    #5
    #gym
  end

  lane :alpha do
    build
    testflight
  end

  lane :release do
    build
    deliver
  end
  
end
