ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "666"

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    cert
    sigh
    Dir.chdir('..') do
      sh 'xcodebuild -resolvePackageDependencies'
    end
    tests
    gym
  end

  lane :release do
    build
    deliver
  end

  lane :alpha do
    build
    testflight(skip_waiting_for_build_processing: true)
  end

  lane :tests do
    scan
  end
end
