ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"

default_platform(:ios)

platform :ios do

  lane :build do
    cert(generate_apple_certs: false)
    sigh
    gym
  end

  lane :alpha do
    build
    pilot
    increment_build_number
  end

  lane :release do
    build
    deliver
    increment_build_number
  end

  lane :test do
    scan
  end
  
end
